-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."beers" add column "international_bitterness_unit" integer
--  null;
