-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO "public"."coffee_roast_level"("text") VALUES (E'LIGHT'), (E'LIGHT_MEDIUM'), (E'MEDIUM'), (E'MEDIUM_DARK'), (E'DARK'), (E'EXTRA_DARK');
