packages:
  - "/"
  - "functions"
  - "functions/_packages/*"
sharedWorkspaceLockfile: false
minimumReleaseAgeExclude:
  - '@tanstack/react-virtual@3.14.2'
  - '@tanstack/virtual-core@3.17.0'
  - graphql@16.14.1
