/**
 * GENERATED — do not edit. Regenerate with:
 *
 *   node src/lib/api/graphcache-schema-codegen.ts
 *
 * `@urql/exchange-graphcache` normalises on `__typename` + `id`. Relay
 * `Node` and global ids were deliberately not adopted (plan §8.3), so ids
 * stay raw uuids and the default keying is right for every object type that
 * has an `id` field. The types below have none — connections, edges,
 * `PageInfo`, the typed error members of every result union, and command
 * payloads — and must be told so explicitly, or graphcache warns on each one
 * and treats it as unkeyable anyway.
 *
 * Derived from `packages/schema/schema.graphql`: every object type that is
 * not a root (`Query` / `Mutation` / `Subscription`), not an introspection
 * type, and has no `id` field. `graphcache-keys.test.ts` fails, with the
 * corrected list, the moment this drifts from the SDL. Rationale and the exact
 * rule: `graphcache-schema-codegen.ts`.
 */

export const KEYLESS_TYPES = [
  "AcceptFriendRequestPayload",
  "ActivityEntryConnection",
  "ActivityEntryEdge",
  "Barcode",
  "BrandConnection",
  "BrandEdge",
  "BrandSearchConnection",
  "BrandSearchEdge",
  "BudgetExceededError",
  "BulkCheckInPayload",
  "CellarConnection",
  "CellarEdge",
  "CellarItemConnection",
  "CellarItemEdge",
  "CellarItemSearchConnection",
  "CellarItemSearchEdge",
  "CellarItemSearchResult",
  "CheckInConnection",
  "CheckInEdge",
  "CollectionStats",
  "ConfirmedItemOnboarding",
  "ConflictError",
  "CreatePlacePayload",
  "DuplicatePlaceCandidate",
  "DuplicatePlaceConnection",
  "DuplicatePlaceEdge",
  "EnrichPlacePayload",
  "ForbiddenError",
  "Friend",
  "FriendConnection",
  "FriendEdge",
  "FriendRequestConnection",
  "FriendRequestEdge",
  "GeocodeResult",
  "GoogleBindingCollision",
  "GooglePlaceDetailsPayload",
  "GooglePlacePrefill",
  "GooglePlaceSuggestion",
  "GooglePlaceSuggestionConnection",
  "GooglePlaceSuggestionEdge",
  "GooglePlacesPayload",
  "ItemBrandConnection",
  "ItemBrandEdge",
  "ItemCheckInConnection",
  "ItemCheckInEdge",
  "ItemConnection",
  "ItemEdge",
  "ItemImageConnection",
  "ItemImageEdge",
  "ItemReviewConnection",
  "ItemReviewEdge",
  "ItemScore",
  "ItemSearchConnection",
  "ItemSearchEdge",
  "ItemTypeCounts",
  "LinkedBarcodeItem",
  "LngLat",
  "MapCluster",
  "MapEntryConnection",
  "MapEntryEdge",
  "MatchSuggestionActionPayload",
  "MatchSuggestionConnection",
  "MatchSuggestionEdge",
  "MenuScanConnection",
  "MenuScanEdge",
  "MutationCreateItemSuccess",
  "MutationUpdateItemSuccess",
  "NearbyPlace",
  "NearbyPlaceConnection",
  "NearbyPlaceEdge",
  "NotFoundError",
  "PageInfo",
  "PlaceBrandConnection",
  "PlaceBrandEdge",
  "PlaceEnrichment",
  "PlaceInteractionConnection",
  "PlaceInteractionEdge",
  "PlaceMenuConnection",
  "PlaceMenuEdge",
  "PlaceMenuItemConnection",
  "PlaceMenuItemEdge",
  "PlacePhotoConnection",
  "PlacePhotoEdge",
  "PlaceReview",
  "PlaceSearchConnection",
  "PlaceSearchEdge",
  "Pong",
  "QueryItemSuccess",
  "RankingEntry",
  "RankingsConnection",
  "RankingsEdge",
  "RecipeConnection",
  "RecipeEdge",
  "RecipeGroupConnection",
  "RecipeGroupEdge",
  "RecipeIngredientConnection",
  "RecipeIngredientEdge",
  "RecipeIngredientsPayload",
  "RecipeInstructionConnection",
  "RecipeInstructionEdge",
  "RecipeInstructionsPayload",
  "RecipePhotoProgress",
  "RecipeReviewConnection",
  "RecipeReviewEdge",
  "RecipeScore",
  "RecipeSearchConnection",
  "RecipeSearchEdge",
  "RecipeSearchResult",
  "RecipeVoteConnection",
  "RecipeVoteEdge",
  "RecipeVotePayload",
  "RecordedPlaceAccess",
  "ReferenceRow",
  "ReferenceRowConnection",
  "ReferenceRowEdge",
  "RejectFriendRequestPayload",
  "RemoveFriendPayload",
  "RemovedRecipeVote",
  "ReorderBandPayload",
  "ReverseGeocodeResult",
  "TierListConnection",
  "TierListEdge",
  "TierListItemConnection",
  "TierListItemEdge",
  "ToggleFavoritePayload",
  "UnlinkedItemBrand",
  "UploadTarget",
  "UserProfileConnection",
  "UserProfileEdge",
  "UserSearchConnection",
  "UserSearchEdge",
  "UserSearchResult",
  "ValidationError",
] as const;

/**
 * graphcache's `keys` map. `() => null` means "embed this in its parent",
 * which is what an id-less value is.
 */
export const graphcacheKeys: Record<string, () => null> = Object.fromEntries(
  KEYLESS_TYPES.map((name) => [name, () => null]),
);
