-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO "public"."coffee_process"("text") VALUES (E'HONEY'), (E'NATURAL_DRY'), (E'PULPED_NATURAL'), (E'PULPED_NATURAL_HONEY'), (E'WASHED'), (E'WET_HULLED');
