-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."cellar_items" add column "percentage_remaining" numeric
--  not null default '100';
