-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE item_favorites drop COLUMN type;
-- ALTER TABLE item_favorites
-- ADD COLUMN type text NOT NULL GENERATED ALWAYS AS (
--     CASE
--         WHEN beer_id IS NOT NULL THEN 'BEER'
--         WHEN wine_id IS NOT NULL THEN 'WINE'
--         WHEN coffee_id IS NOT NULL THEN 'COFFEE'
--         ELSE 'SPIRIT'
--     END
-- ) STORED;
