-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO "public"."wine_variety"("text") VALUES (E'ASTI'), (E'CAVA'), (E'CHAMPAGNE'), (E'CRÉMANT');
