-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."cellars" add column "privacy" text
--  not null default 'PRIVATE';
