"use client";

import "@fontsource/inter";
import { NhostClient, NhostProvider } from "@nhost/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NhostUrqlProvider } from "@/utilities/UrqlProvider";
import ThemeRegistry from "@/components/ThemeRegistry";
import { Box, GlobalStyles } from "@mui/joy";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const nhost = new NhostClient({
  region: process.env.NEXT_PUBLIC_NHOST_REGION,
  subdomain: process.env.NEXT_PUBLIC_NHOST_SUBDOMAIN,
  graphqlUrl: process.env.NEXT_PUBLIC_NHOST_GRAPHQL_URL,
  authUrl: process.env.NEXT_PUBLIC_NHOST_AUTH_URL,
  storageUrl: process.env.NEXT_PUBLIC_NHOST_STORAGE_URL,
  functionsUrl: process.env.NEXT_PUBLIC_NHOST_FUNCTIONS_URL,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalStyles
          styles={{
            svg: {
              color: "var(--Icon-color)",
              margin: "var(--Icon-margin)",
              fontSize: "var(--Icon-fontSize, 20px)",
              width: "0.75em",
              height: "0.75em",
            },
          }}
        />
        <NhostProvider nhost={nhost}>
          <NhostUrqlProvider nhost={nhost}>
            <ThemeRegistry>
              <Box sx={{ height: "100vh", width: "100vw" }}>{children}</Box>
            </ThemeRegistry>
          </NhostUrqlProvider>
        </NhostProvider>
      </body>
    </html>
  );
}
