-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO "public"."friend_request_status"("text") VALUES (E'PENDING'), (E'ACCEPTED');
