-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."wines" add column "alcohol_content_percentage" numeric
--  null;
