-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO "public"."permission_type"("text") VALUES (E'PRIVATE'), (E'PUBLIC'), (E'FRIENDS');
