import type { CategoryIdentity, ItemType } from "../types";

// Identity-based category mappings
// identityScore: "How central is [item type] to this category's identity?"
//   0.9-1.0 = This IS a [type] place (winery, brewery, coffee_shop)
//   0.6-0.89 = [type] is core to this place (bar for spirits, steakhouse for wine)
//   0.3-0.59 = [type] is present but not central (liquor_store, some restaurants)
//   0.0-0.29 = [type] is incidental (hotel, grocery_store)
export const ITEM_TYPE_CATEGORY_MAPPINGS: Record<ItemType, CategoryIdentity[]> =
  {
    wine: [
      { category: "winery", identityScore: 0.95 },
      { category: "wine_bar", identityScore: 0.95 },
      { category: "wine_tasting_room", identityScore: 0.95 },
      { category: "beer_wine_and_spirits", identityScore: 0.7 },
      { category: "wine_wholesaler", identityScore: 0.6 },
      { category: "steakhouse", identityScore: 0.6 },
      { category: "french_restaurant", identityScore: 0.6 },
      { category: "italian_restaurant", identityScore: 0.55 },
      { category: "tapas_bar", identityScore: 0.5 },
      { category: "liquor_store", identityScore: 0.5 },
      { category: "bar", identityScore: 0.4 },
      { category: "cocktail_bar", identityScore: 0.4 },
      { category: "lounge", identityScore: 0.4 },
      { category: "gastropub", identityScore: 0.4 },
      { category: "japanese_restaurant", identityScore: 0.3 },
      { category: "sushi_restaurant", identityScore: 0.3 },
      { category: "restaurant", identityScore: 0.25 },
      { category: "specialty_grocery_store", identityScore: 0.25 },
      { category: "organic_grocery_store", identityScore: 0.2 },
      { category: "resort", identityScore: 0.2 },
      { category: "hotel", identityScore: 0.15 },
      { category: "casino", identityScore: 0.15 },
      { category: "grocery_store", identityScore: 0.15 },
      { category: "supermarket", identityScore: 0.15 },
    ],

    beer: [
      { category: "brewery", identityScore: 0.95 },
      { category: "beer_bar", identityScore: 0.95 },
      { category: "beer_garden", identityScore: 0.9 },
      { category: "pub", identityScore: 0.85 },
      { category: "sports_bar", identityScore: 0.7 },
      { category: "beer_wine_and_spirits", identityScore: 0.7 },
      { category: "gastropub", identityScore: 0.65 },
      { category: "bar", identityScore: 0.6 },
      { category: "beverage_store", identityScore: 0.55 },
      { category: "music_venue", identityScore: 0.5 },
      { category: "liquor_store", identityScore: 0.5 },
      { category: "tapas_bar", identityScore: 0.35 },
      { category: "mexican_restaurant", identityScore: 0.35 },
      { category: "japanese_restaurant", identityScore: 0.3 },
      { category: "lounge", identityScore: 0.3 },
      { category: "thai_restaurant", identityScore: 0.25 },
      { category: "chinese_restaurant", identityScore: 0.25 },
      { category: "sushi_restaurant", identityScore: 0.25 },
      { category: "restaurant", identityScore: 0.2 },
      { category: "grocery_store", identityScore: 0.2 },
      { category: "supermarket", identityScore: 0.2 },
      { category: "specialty_grocery_store", identityScore: 0.2 },
      { category: "casino", identityScore: 0.2 },
      { category: "cafe", identityScore: 0.15 },
      { category: "resort", identityScore: 0.15 },
      { category: "hotel", identityScore: 0.1 },
    ],

    spirit: [
      { category: "distillery", identityScore: 0.95 },
      { category: "whiskey_bar", identityScore: 0.95 },
      { category: "cocktail_bar", identityScore: 0.9 },
      { category: "liquor_store", identityScore: 0.75 },
      { category: "bar", identityScore: 0.7 },
      { category: "beer_wine_and_spirits", identityScore: 0.7 },
      { category: "lounge", identityScore: 0.65 },
      { category: "pub", identityScore: 0.55 },
      { category: "beverage_store", identityScore: 0.55 },
      { category: "sake_bar", identityScore: 0.5 },
      { category: "steakhouse", identityScore: 0.45 },
      { category: "gastropub", identityScore: 0.45 },
      { category: "japanese_restaurant", identityScore: 0.4 },
      { category: "mexican_restaurant", identityScore: 0.4 },
      { category: "casino", identityScore: 0.4 },
      { category: "wine_bar", identityScore: 0.35 },
      { category: "sushi_restaurant", identityScore: 0.35 },
      { category: "french_restaurant", identityScore: 0.35 },
      { category: "music_venue", identityScore: 0.35 },
      { category: "wine_wholesaler", identityScore: 0.3 },
      { category: "resort", identityScore: 0.25 },
      { category: "restaurant", identityScore: 0.2 },
      { category: "specialty_grocery_store", identityScore: 0.2 },
      { category: "hotel", identityScore: 0.15 },
      { category: "organic_grocery_store", identityScore: 0.15 },
      { category: "grocery_store", identityScore: 0.1 },
      { category: "supermarket", identityScore: 0.1 },
    ],

    coffee: [
      { category: "coffee_shop", identityScore: 0.95 },
      { category: "coffee_roastery", identityScore: 0.95 },
      { category: "cafe", identityScore: 0.9 },
      { category: "italian_restaurant", identityScore: 0.25 },
      { category: "french_restaurant", identityScore: 0.2 },
      { category: "specialty_grocery_store", identityScore: 0.2 },
      { category: "organic_grocery_store", identityScore: 0.15 },
      { category: "restaurant", identityScore: 0.1 },
      { category: "hotel", identityScore: 0.1 },
      { category: "resort", identityScore: 0.1 },
      { category: "gastropub", identityScore: 0.1 },
      { category: "lounge", identityScore: 0.1 },
      { category: "grocery_store", identityScore: 0.1 },
      { category: "supermarket", identityScore: 0.1 },
      { category: "bar", identityScore: 0.05 },
      { category: "casino", identityScore: 0.05 },
      { category: "music_venue", identityScore: 0.05 },
    ],

    sake: [
      { category: "sake_bar", identityScore: 0.95 },
      { category: "japanese_restaurant", identityScore: 0.8 },
      { category: "sushi_restaurant", identityScore: 0.75 },
      { category: "liquor_store", identityScore: 0.5 },
      { category: "beer_wine_and_spirits", identityScore: 0.5 },
      { category: "cocktail_bar", identityScore: 0.35 },
      { category: "specialty_grocery_store", identityScore: 0.35 },
      { category: "bar", identityScore: 0.3 },
      { category: "wine_bar", identityScore: 0.3 },
      { category: "restaurant", identityScore: 0.15 },
      { category: "hotel", identityScore: 0.1 },
      { category: "resort", identityScore: 0.1 },
      { category: "casino", identityScore: 0.1 },
    ],
  };
