-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO "public"."wine_variety"("text") VALUES (E'ALBARIÑO_/_ALVARINHO'), (E'ARNEIS'), (E'CHARDONNAY'), (E'CHENIN_BLANC'), (E'FURMINT'), (E'GARGANEGA'), (E'GEWÜRZTRAMINER'), (E'GRÜNER_VELTLINER'), (E'MALVASIA'), (E'MARSANNE'), (E'MÜLLER-THURGAU'), (E'MUSCADET'), (E'PINOT_BLANC'), (E'PINOT_GRIGIO_/_PINOT_GRIS'), (E'PROSECCO'), (E'ROUSSANNE'), (E'RIESLING'), (E'SAUVIGNON_BLANC'), (E'SEMILLON'), (E'TORRONTES'), (E'VERDEJO'), (E'VIOGNIER');
