on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.15.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "2105893"
          username: "Release Changelog"
          avatar_url: ${{secrets.DISCORD_AVATAR_URL}}
          content: "||@everyone||"
          footer_title: "Changelog"
          footer_icon_url: ${{secrets.DISCORD_AVATAR_URL}}
          footer_timestamp: true
