on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.CELLAR_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.CELLAR_ASSISTANT_PRIVATE_KEY }}
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 100
      - name: Deploy Prod
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin production
          git checkout production
          git merge --ff-only ${{ github.sha }}
          git push
